### ISSUE TITLE
Installing error: Can't enable it

### ISSUE THREAD

**Issue by TheGitMpeg** [CodeFHD/OptiCore#17]
Hello! I have a problem: I can't enable that addon.
Every time I enable it, it says me: "No module named OptiCore-1"
My Blender version: 3.4.1.0
I need a solution, please.

**Comment by CodeFHD** [comment]
Hi,
this problem was reported before, and seems to be connected to the release version specifically. See here for a solution:

**Comment by CodeFHD** [comment]
Hi,
this problem was reported before and seems to be specific to the installation of the "1.0 release". See here for details how to get that to work:
https://github.com/CodeFHD/OptiCore/issues/4

In any case, I wouldn't really recommend to donwload the release version, but rather the latest code. In case you don't know how, here is a picture tzhat highlights the correct buttons on the main page of the repository:

![opticore_latest](https://user-images.githubusercontent.com/48182552/215702008-64e88f91-a221-4e39-88b4-130e2f5198df.png)

**Comment by CodeFHD** [comment]
Closed because of no further feedback.
