### ISSUE TITLE
homogenies scattering volume

### ISSUE THREAD

**Issue by ciriguaya** [CodeFHD/OptiCore#20]
Hi, 

I'm very impressed by this addon for blender, but am currently stuck getting the homogenies scattering volume to work, could you give us some instructions? 

thx

**Comment by CodeFHD** [comment]
Sorry for not answering this sooner, I was not very active for some time and then forgot about this issue being open....

In any case, I will have to divert this topic here, becasue it is not an issue of OptiCore, which only generates geometry. The volumetrics are part of a rendering engine. Probably, you refered to LuxCoreRender because of my example videos. 

There are some tutorials available for this rendering engine, for example this one:
https://www.youtube.com/watch?v=fn9bTSNST20

or you could try asking on the LuxCore forum or discord channel:
http://forums.luxcorerender.org/
https://discord.gg/chPGsKV

If you have further questions with relevance to OptiCore, you might consider to use the discussions section as well, as issues should be reserved for bug reports, feature request, etc.
